# 循环神经网络

In [1]:
import torch
import torch.nn

循环神经元

In [2]:
cell = torch.nn.LSTMCell(input_size=3, hidden_size=5)
for name, param in cell.named_parameters():
    print ('{} = {}'.format(name, param))

weight_ih = Parameter containing:
tensor([[ 0.1546, -0.4201,  0.3069],
        [-0.2943, -0.4141,  0.3779],
        [-0.1165,  0.4225,  0.2909],
        [-0.2210,  0.1744,  0.0445],
        [-0.0775, -0.0825,  0.2698],
        [-0.4021,  0.1798, -0.1067],
        [ 0.2447,  0.1739,  0.3121],
        [ 0.3183,  0.4011,  0.4168],
        [ 0.2450,  0.2716, -0.2862],
        [-0.3181,  0.0293,  0.3267],
        [ 0.0849,  0.2340, -0.1914],
        [ 0.3657, -0.3483,  0.2243],
        [-0.3867,  0.0610,  0.1920],
        [ 0.2874, -0.1962, -0.1405],
        [ 0.3990, -0.3319, -0.3178],
        [-0.2392,  0.0449, -0.0476],
        [ 0.4250,  0.2782,  0.1471],
        [ 0.3917,  0.1959, -0.1446],
        [ 0.4112, -0.3560, -0.4284],
        [ 0.2853,  0.1100,  0.2023]])
weight_hh = Parameter containing:
tensor([[-0.3648,  0.4430, -0.3348,  0.4109, -0.1680],
        [ 0.1527, -0.2936, -0.2579, -0.4133,  0.3711],
        [ 0.1496,  0.0196,  0.3598, -0.0696, -0.3412],
        [-0.2432, -0.3334,

In [3]:
seq_len, batch_size = 6, 2
input_size, hidden_size = 3, 5
cell = torch.nn.LSTMCell(input_size=input_size, hidden_size=hidden_size)
inputs = torch.randn(seq_len, batch_size, input_size)
h = torch.randn(batch_size, hidden_size)
c = torch.randn(batch_size, hidden_size)
hs = []
for t in range(seq_len):
    h, c = cell(inputs[t], (h, c))
    hs.append(h)
outputs = torch.stack(hs)
outputs

tensor([[[ 0.0732,  0.1581,  0.3137, -0.2106, -0.1092],
         [ 0.1603, -0.2076, -0.1196, -0.1444, -0.1216]],

        [[ 0.2538, -0.0410,  0.0857, -0.2496, -0.0189],
         [ 0.1475, -0.1631, -0.3240, -0.1581, -0.0433]],

        [[ 0.3371, -0.0973, -0.1303, -0.2868, -0.0598],
         [ 0.1204,  0.2496, -0.0261, -0.0944,  0.1428]],

        [[ 0.1067,  0.2162, -0.0122, -0.0719,  0.1257],
         [ 0.2920, -0.0272, -0.2666, -0.2972,  0.1752]],

        [[ 0.1566,  0.1770, -0.1212, -0.1658,  0.1794],
         [ 0.2071,  0.0663, -0.1071, -0.1625,  0.1738]],

        [[ 0.1330,  0.0043, -0.2234, -0.1526,  0.1552],
         [ 0.1273,  0.2843, -0.0382, -0.1195,  0.1782]]])

循环神经网络

In [4]:
num_layers = 2
seq_len, batch_size = 6, 2
input_size, hidden_size = 3, 5
rnn = torch.nn.GRU(input_size, hidden_size, num_layers=num_layers)
inputs = torch.randn(seq_len, batch_size, input_size)
h0 = torch.randn(num_layers, batch_size, hidden_size)
outputs, hn = rnn(inputs, h0)
outputs

tensor([[[ 0.3042, -0.0433,  0.2862, -0.0866,  0.0233],
         [ 1.1850, -0.3314,  0.3698,  0.0435,  0.3782]],

        [[ 0.5028,  0.0474,  0.4993, -0.0569, -0.1327],
         [ 0.8510, -0.2051,  0.1971, -0.1291,  0.1303]],

        [[ 0.5346,  0.1130,  0.5334, -0.0580, -0.1849],
         [ 0.7298, -0.0204,  0.2554, -0.3126, -0.0835]],

        [[ 0.4235,  0.1390,  0.4812,  0.0389, -0.1578],
         [ 0.5358,  0.0757,  0.3022, -0.2219, -0.1193]],

        [[ 0.3670,  0.1709,  0.4674,  0.0571, -0.1334],
         [ 0.4393,  0.1196,  0.3984, -0.1327, -0.1680]],

        [[ 0.3976,  0.2156,  0.4842, -0.0041, -0.1286],
         [ 0.4780,  0.1968,  0.4448, -0.1736, -0.1918]]])

In [5]:
num_layers = 2
hidden_size = 3
bidirectional = True
rnn = torch.nn.RNN(input_size=10, hidden_size=hidden_size, num_layers=num_layers, bidirectional=bidirectional)
inputs = torch.randn(5, 3, 10)
h0 = torch.randn(num_layers * 2 if bidirectional else num_layers, 3, hidden_size)
outputs, hn = rnn(inputs, h0)
for param in rnn.parameters():
    print (param)
    # print (param.size())

Parameter containing:
tensor([[ 0.5751, -0.2216,  0.2251,  0.0647,  0.2716,  0.1060, -0.0162,
          0.0417, -0.3813,  0.3719],
        [-0.3064, -0.1623, -0.2981,  0.0982, -0.1122,  0.0357, -0.3964,
          0.5385,  0.0034, -0.2868],
        [ 0.1982, -0.0780, -0.4070, -0.3685, -0.4458, -0.3976,  0.3372,
          0.3086, -0.3340, -0.0211]])
Parameter containing:
tensor([[-0.5260, -0.1456,  0.3338],
        [-0.0070, -0.2073, -0.5632],
        [ 0.1125,  0.5314,  0.2881]])
Parameter containing:
tensor([ 0.1285, -0.1500,  0.4653])
Parameter containing:
tensor([ 0.4319,  0.3306, -0.0562])
Parameter containing:
tensor([[-0.2565, -0.0548,  0.0921, -0.2308, -0.3747,  0.0458, -0.5546,
          0.0367, -0.1622,  0.3625],
        [-0.0949, -0.1870,  0.2820,  0.3193, -0.4838,  0.3729,  0.3045,
         -0.2570,  0.4971, -0.0430],
        [ 0.5405,  0.2729,  0.2505,  0.2948, -0.3279, -0.3744, -0.1306,
         -0.0003,  0.3529, -0.2866]])
Parameter containing:
tensor([[-0.4026,  0.4768,  