# 卷积神经网络

In [1]:
import torch
import torch.nn as nn

卷积层

In [2]:
conv = torch.nn.Conv2d(16, 33, kernel_size=(3, 5), 
        stride=(2, 1), padding=(4, 2), dilation=(3, 1))
inputs = torch.randn(20, 16, 50, 100)
outputs = conv(inputs)
outputs.size()

torch.Size([20, 33, 26, 100])

池化层

In [3]:
pool = nn.MaxPool1d(kernel_size=2, stride=2)
inputs = torch.randn(20, 16, 100)
outputs = pool(inputs)
outputs.size()

torch.Size([20, 16, 50])

In [4]:
inputs = torch.tensor([[[1, 2, 3, 4, 5]]], dtype=torch.float)
pool = nn.MaxPool1d(kernel_size=2, stride=2, return_indices=True)
outputs, indices = pool(inputs)
unpool = nn.MaxUnpool1d(kernel_size=2, stride=2)
recovers = unpool(outputs, indices)
recovers

tensor([[[0., 2., 0., 4.]]])

In [5]:
inputs = torch.tensor([[[1, 2, 3, 4, 5]]], dtype=torch.float)
pool = nn.MaxPool1d(kernel_size=2, stride=2, return_indices=True)
outputs, indices = pool(inputs)
unpool = nn.MaxUnpool1d(kernel_size=2, stride=2)
recovers = unpool(outputs, indices, output_size=inputs.size())
recovers

tensor([[[0., 2., 0., 4., 0.]]])

In [6]:
pool = nn.MaxPool1d(2, stride=2, return_indices=True)
unpool = nn.MaxUnpool1d(2, stride=2)
inputs = torch.tensor([[[1, 2, 3, 4, 5, 6, 7, 8]]], dtype=torch.float)
outputs, indices = pool(inputs)
unpool(outputs, indices)

tensor([[[0., 2., 0., 4., 0., 6., 0., 8.]]])

上采样层

In [7]:
inputs = torch.tensor([[[1, 0, 2]]], dtype=torch.float)
# m = nn.Upsample(scale_factor=3, mode='nearest')
m = nn.Upsample(scale_factor=3, mode='linear')
inputs, m(inputs)

C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py:2539: UserWarning: Default upsampling behavior when mode=linear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))


(tensor([[[1., 0., 2.]]]),
 tensor([[[1.0000, 1.0000, 0.6667, 0.3333, 0.0000, 0.6667, 1.3333, 2.0000,
           2.0000]]]))

In [8]:
inputs = torch.tensor([[[1, 0, 2]]], dtype=torch.float)
# m = nn.Upsample(size=9, mode='nearest')
m = nn.Upsample(size=8, mode='linear')
inputs, m(inputs), m(inputs) * 7

(tensor([[[1., 0., 2.]]]),
 tensor([[[1.0000, 0.9375, 0.5625, 0.1875, 0.3750, 1.1250, 1.8750, 2.0000]]]),
 tensor([[[ 7.0000,  6.5625,  3.9375,  1.3125,  2.6250,  7.8750, 13.1250,
           14.0000]]]))

In [9]:
inputs = torch.arange(0, 4).reshape(1, 1, 4)
inputs = torch.tensor([[[1, 0, 2]]], dtype=torch.float)
# m = nn.Upsample(scale_factor=2, mode='nearest')
m = nn.Upsample(scale_factor=2, mode='linear')
inputs, m(inputs)

(tensor([[[1., 0., 2.]]]),
 tensor([[[1.0000, 0.7500, 0.2500, 0.5000, 1.5000, 2.0000]]]))

In [10]:
inputs = torch.arange(1, 5, dtype=torch.float).view(1, 1, 2, 2)
upsample = nn.Upsample(scale_factor=2, mode='nearest')
upsample(inputs)

tensor([[[[1., 1., 2., 2.],
          [1., 1., 2., 2.],
          [3., 3., 4., 4.],
          [3., 3., 4., 4.]]]])

补全层

In [11]:
inputs = torch.arange(25, dtype=torch.float).view(1, 1, 5, 5)
pad = nn.ConstantPad2d([1, 1, 1, 1], value=-1)
outputs = pad(inputs)
inputs, outputs

(tensor([[[[ 0.,  1.,  2.,  3.,  4.],
           [ 5.,  6.,  7.,  8.,  9.],
           [10., 11., 12., 13., 14.],
           [15., 16., 17., 18., 19.],
           [20., 21., 22., 23., 24.]]]]),
 tensor([[[[-1., -1., -1., -1., -1., -1., -1.],
           [-1.,  0.,  1.,  2.,  3.,  4., -1.],
           [-1.,  5.,  6.,  7.,  8.,  9., -1.],
           [-1., 10., 11., 12., 13., 14., -1.],
           [-1., 15., 16., 17., 18., 19., -1.],
           [-1., 20., 21., 22., 23., 24., -1.],
           [-1., -1., -1., -1., -1., -1., -1.]]]]))

In [12]:
inputs = torch.arange(25, dtype=torch.float).view(1, 1, 5, 5)
pad = nn.ReplicationPad2d([1, 1, 1, 1])
outputs = pad(inputs)
inputs, outputs

(tensor([[[[ 0.,  1.,  2.,  3.,  4.],
           [ 5.,  6.,  7.,  8.,  9.],
           [10., 11., 12., 13., 14.],
           [15., 16., 17., 18., 19.],
           [20., 21., 22., 23., 24.]]]]),
 tensor([[[[ 0.,  0.,  1.,  2.,  3.,  4.,  4.],
           [ 0.,  0.,  1.,  2.,  3.,  4.,  4.],
           [ 5.,  5.,  6.,  7.,  8.,  9.,  9.],
           [10., 10., 11., 12., 13., 14., 14.],
           [15., 15., 16., 17., 18., 19., 19.],
           [20., 20., 21., 22., 23., 24., 24.],
           [20., 20., 21., 22., 23., 24., 24.]]]]))

In [13]:
inputs = torch.arange(25, dtype=torch.float).view(1, 1, 5, 5)
pad = nn.ReflectionPad2d([1, 1, 1, 1])
outputs = pad(inputs)
inputs, outputs

(tensor([[[[ 0.,  1.,  2.,  3.,  4.],
           [ 5.,  6.,  7.,  8.,  9.],
           [10., 11., 12., 13., 14.],
           [15., 16., 17., 18., 19.],
           [20., 21., 22., 23., 24.]]]]),
 tensor([[[[ 6.,  5.,  6.,  7.,  8.,  9.,  8.],
           [ 1.,  0.,  1.,  2.,  3.,  4.,  3.],
           [ 6.,  5.,  6.,  7.,  8.,  9.,  8.],
           [11., 10., 11., 12., 13., 14., 13.],
           [16., 15., 16., 17., 18., 19., 18.],
           [21., 20., 21., 22., 23., 24., 23.],
           [16., 15., 16., 17., 18., 19., 18.]]]]))

In [14]:
inputs = torch.arange(12, dtype=torch.float).view(1, 1, 3, 4)
pad = nn.ConstantPad2d(padding=[1, 1, 1, 1], value=-1)
print ('常数补全 = {}'.format(pad(inputs)))
pad = nn.ReplicationPad2d(padding=[1, 1, 1, 1])
print ('重复补全 = {}'.format(pad(inputs)))
pad = nn.ReflectionPad2d(padding=[1, 1, 1, 1])
print ('反射补全 = {}'.format(pad(inputs)))

常数补全 = tensor([[[[-1., -1., -1., -1., -1., -1.],
          [-1.,  0.,  1.,  2.,  3., -1.],
          [-1.,  4.,  5.,  6.,  7., -1.],
          [-1.,  8.,  9., 10., 11., -1.],
          [-1., -1., -1., -1., -1., -1.]]]])
重复补全 = tensor([[[[ 0.,  0.,  1.,  2.,  3.,  3.],
          [ 0.,  0.,  1.,  2.,  3.,  3.],
          [ 4.,  4.,  5.,  6.,  7.,  7.],
          [ 8.,  8.,  9., 10., 11., 11.],
          [ 8.,  8.,  9., 10., 11., 11.]]]])
反射补全 = tensor([[[[ 5.,  4.,  5.,  6.,  7.,  6.],
          [ 1.,  0.,  1.,  2.,  3.,  2.],
          [ 5.,  4.,  5.,  6.,  7.,  6.],
          [ 9.,  8.,  9., 10., 11., 10.],
          [ 5.,  4.,  5.,  6.,  7.,  6.]]]])
