# 张量的构造和使用

In [1]:
import torch

构造张量

In [2]:
t1 = torch.tensor([0., 1., 2.])
t2 = torch.tensor([[0., 1., 2.], [3., 4., 5.], [6., 7., 8.]])
t3 = torch.tensor([[[0., 1., 2.], [3., 4., 5.], [6., 7., 8.]],
        [[9., 10., 11.], [12., 13., 14.], [15., 16., 17.]],
        [[18., 19., 20.], [21., 22., 23.], [24., 25., 26.]]])

In [3]:
t1 = torch.empty(2) # 未初始化
t2 = torch.zeros(2, 2) # 各元素值.
t3 = torch.ones(2, 2, 2) # 各元素值为1.
t4 = torch.full((2, 2, 2, 2), 3.) # 各元素值为3.

In [4]:
t2 = torch.empty(2, 2)
t2[0, 0] = 0.
t2[0, 1] = 1.
t2[1, 0] = 2.
t2[1, 1] = 3.
print(t2)
print(t2.equal(torch.tensor([[0., 1.], [2., 3.]])))

tensor([[ 0.,  1.],
        [ 2.,  3.]])
True


In [5]:
torch.zeros(2, 3, 4)
torch.ones(2, 3, 4)

tensor([[[ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.]],

        [[ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.]]])

In [6]:
torch.ones_like(t2)

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [7]:
torch.linspace(0, 3, steps=4)

tensor([ 0.,  1.,  2.,  3.])

张量的性质

In [8]:
print('data = {}'.format(t2))
print('size = {}'.format(t2.size()))
print('dim = {}'.format(t2.dim()))
print('numel = {}'.format(t2.numel()))

data = tensor([[ 0.,  1.],
        [ 2.,  3.]])
size = torch.Size([2, 2])
dim = 2
numel = 4


In [9]:
t2.dtype

torch.float32

改变张量的大小

In [10]:
tc = torch.arange(12) # 张量大小 (12,)
print('tc = {}'.format(tc))
t322 = tc.reshape(3, 2, 2) # 张量大小 (3, 2, 2)
print('t322 = {}'.format(t322))
t43 = t322.reshape(4, 3) # 张量大小 (4, 3)
print('t43 = {}'.format(t43))

tc = tensor([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,
         10.,  11.])
t322 = tensor([[[  0.,   1.],
         [  2.,   3.]],

        [[  4.,   5.],
         [  6.,   7.]],

        [[  8.,   9.],
         [ 10.,  11.]]])
t43 = tensor([[  0.,   1.,   2.],
        [  3.,   4.,   5.],
        [  6.,   7.,   8.],
        [  9.,  10.,  11.]])


In [11]:
t12 = torch.tensor([[5., -9.],])
t21 = t12.transpose(0, 1)
print('t21 = {}'.format(t21))
t21 = t12.t()
print('t21 = {}'.format(t21))

t21 = tensor([[ 5.],
        [-9.]])
t21 = tensor([[ 5.],
        [-9.]])


In [12]:
t12 = torch.tensor([[5., -9.],])
print('t12 = {}'.format(t12))
t34 = t12.repeat(3, 2)
print('t34 = {}'.format(t34))

t12 = tensor([[ 5., -9.]])
t34 = tensor([[ 5., -9.,  5., -9.],
        [ 5., -9.,  5., -9.],
        [ 5., -9.,  5., -9.]])


In [13]:
t44 = torch.arange(16).reshape(4, 4)
print('t44 = {}'.format(t44))
t23 = t44[1:-1, :3]
print('t23 = {}'.format(t23))

t44 = tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.],
        [ 12.,  13.,  14.,  15.]])
t23 = tensor([[  4.,   5.,   6.],
        [  8.,   9.,  10.]])


张量的数学运算

In [14]:
tl = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
tr = torch.tensor([[7., 8., 9.], [10., 11., 12.]])
print(tl + tr) # 加法
print(tl - tr) # 减法
print(tl * tr) # 乘法
print(tl / tr) # 除法
print(tl ** tr) # 有理数次乘方
print(tl ** (1 / tr)) # 有理数次开方

tensor([[  8.,  10.,  12.],
        [ 14.,  16.,  18.]])
tensor([[-6., -6., -6.],
        [-6., -6., -6.]])
tensor([[  7.,  16.,  27.],
        [ 40.,  55.,  72.]])
tensor([[ 0.1429,  0.2500,  0.3333],
        [ 0.4000,  0.4545,  0.5000]])
tensor([[ 1.0000e+00,  2.5600e+02,  1.9683e+04],
        [ 1.0486e+06,  4.8828e+07,  2.1768e+09]])
tensor([[ 1.0000,  1.0905,  1.1298],
        [ 1.1487,  1.1576,  1.1610]])


In [15]:
print(torch.zeros(3, 4) + 5) # 得到各元素全为5的大小为(3,4)的张量
print(-6 * torch.ones(2)) # 得到各元素全为-6的大小为(2,)的张量
print(torch.ones(2, 3, 4) + torch.ones(4)) # 得到各元素全为2的大小为(2,3,4)的张量

tensor([[ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.]])
tensor([-6., -6.])
tensor([[[ 2.,  2.,  2.,  2.],
         [ 2.,  2.,  2.,  2.],
         [ 2.,  2.,  2.,  2.]],

        [[ 2.,  2.,  2.,  2.],
         [ 2.,  2.,  2.,  2.],
         [ 2.,  2.,  2.,  2.]]])


In [16]:
t234 = torch.arange(24).reshape(2, 3, 4)
print('sqrt = {}'.format(t234.sqrt()))
print('sum = {}'.format(t234.sum()))
print('prod = {}'.format(t234.prod()))
print('norm(2) = {}'.format(t234.norm(2)))
print('cumsum = {}'.format(t234.cumsum(dim=0)))
print('cumprod = {}'.format(t234.cumprod(dim=1)))

sqrt = tensor([[[ 0.0000,  1.0000,  1.4142,  1.7321],
         [ 2.0000,  2.2361,  2.4495,  2.6458],
         [ 2.8284,  3.0000,  3.1623,  3.3166]],

        [[ 3.4641,  3.6056,  3.7417,  3.8730],
         [ 4.0000,  4.1231,  4.2426,  4.3589],
         [ 4.4721,  4.5826,  4.6904,  4.7958]]])
sum = 276.0
prod = 0.0
norm(2) = 65.75712585449219
cumsum = tensor([[[  0.,   1.,   2.,   3.],
         [  4.,   5.,   6.,   7.],
         [  8.,   9.,  10.,  11.]],

        [[ 12.,  14.,  16.,  18.],
         [ 20.,  22.,  24.,  26.],
         [ 28.,  30.,  32.,  34.]]])
cumprod = tensor([[[    0.,     1.,     2.,     3.],
         [    0.,     5.,    12.,    21.],
         [    0.,    45.,   120.,   231.]],

        [[   12.,    13.,    14.,    15.],
         [  192.,   221.,   252.,   285.],
         [ 3840.,  4641.,  5544.,  6555.]]])


In [17]:
tp = torch.pow(torch.arange(1, 4), torch.arange(3))
print('pow = {}'.format(tp))
te = torch.exp(torch.tensor([0.1, -0.01]))
print('exp = {}'.format(te))
ts = torch.sin(torch.tensor([[3.14 / 4,],]))
print('sin = {}'.format(ts))

pow = tensor([ 1.,  2.,  9.])
exp = tensor([ 1.1052,  0.9900])
sin = tensor([[ 0.7068]])


In [18]:
t5 = torch.arange(5)
tf = torch.frac(t5 * 0.3)
print('frac = {}'.format(tf))
tc = torch.clamp(t5, 0.5, 3.5)
print('clamp = {}'.format(tc))

frac = tensor([ 0.0000,  0.3000,  0.6000,  0.9000,  0.2000])
clamp = tensor([ 0.5000,  1.0000,  2.0000,  3.0000,  3.5000])


张量的拼接

In [19]:
tp = torch.arange(12).reshape(3, 4)
tn = -tp
tc0 = torch.cat([tp, tn], 0)
print('tc0 = {}'.format(tc0))
tc1 = torch.cat([tp, tp, tn, tn], 1)
print('tc1 = {}'.format(tc1))

tc0 = tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.],
        [ -0.,  -1.,  -2.,  -3.],
        [ -4.,  -5.,  -6.,  -7.],
        [ -8.,  -9., -10., -11.]])
tc1 = tensor([[  0.,   1.,   2.,   3.,   0.,   1.,   2.,   3.,  -0.,  -1.,
          -2.,  -3.,  -0.,  -1.,  -2.,  -3.],
        [  4.,   5.,   6.,   7.,   4.,   5.,   6.,   7.,  -4.,  -5.,
          -6.,  -7.,  -4.,  -5.,  -6.,  -7.],
        [  8.,   9.,  10.,  11.,   8.,   9.,  10.,  11.,  -8.,  -9.,
         -10., -11.,  -8.,  -9., -10., -11.]])


In [20]:
tp = torch.arange(12).reshape(3, 4)
tn = -tp
ts0 = torch.stack([tp, tn], 0)
print('ts0 = {}'.format(ts0))
ts1 = torch.stack([tp, tp, tn, tn], 1)
print('ts1 = {}'.format(ts1))

ts0 = tensor([[[  0.,   1.,   2.,   3.],
         [  4.,   5.,   6.,   7.],
         [  8.,   9.,  10.,  11.]],

        [[ -0.,  -1.,  -2.,  -3.],
         [ -4.,  -5.,  -6.,  -7.],
         [ -8.,  -9., -10., -11.]]])
ts1 = tensor([[[  0.,   1.,   2.,   3.],
         [  0.,   1.,   2.,   3.],
         [ -0.,  -1.,  -2.,  -3.],
         [ -0.,  -1.,  -2.,  -3.]],

        [[  4.,   5.,   6.,   7.],
         [  4.,   5.,   6.,   7.],
         [ -4.,  -5.,  -6.,  -7.],
         [ -4.,  -5.,  -6.,  -7.]],

        [[  8.,   9.,  10.,  11.],
         [  8.,   9.,  10.,  11.],
         [ -8.,  -9., -10., -11.],
         [ -8.,  -9., -10., -11.]]])
